### ISSUE TITLE
[RS01] Implementar Baterías de voltaje ajustable

### ISSUE THREAD

**Issue by IsmaelAlvarez** [IsmaelAlvarez/logisim#1]
La "protoboard" deberá soportar distintos voltajes. Para esto se ha de implementar baterías de voltaje entre 4 Volts y 20 Volts, en valores enteros como un atributo del objeto.

Ref: RU01
- [x] Initialization
- [x] Concept Location
- [x] Impact Analysis
- [x] Prefactoring
- [x] Change Propagation
- [x] Verification
- [x] Postfactoring

**Comment by vrotmanh** [comment]
**Initialization**
Se pondrá un selector que dará todas las opciones de valores enteros entre 4 y 20 volts. Por defecto estará seleccionado el 5.

**Comment by vrotmanh** [comment]
**Concept Location**
protosim.components.VoltageGenerator, logisim.data.Voltage

**Comment by vrotmanh** [comment]
**Impact Analysis**
TODO

**Comment by vrotmanh** [comment]
**Prefactoring**
En la clase Voltage: Se agregan todas las opciones de valores entre 4-20. Luego se agrega como atributo el valor del voltage, este se recibe en el constructor y se crea un método getVoltage que entrega este valor.

En la clase VoltageGenerator: Se setea que por defecto venga el voltage de 5 desde el constructor. En el método instanceAttributeChanged, se incluye que se cambie el voltage cuando este es cambiado por el user.

**Comment by vrotmanh** [comment]
**Change Propagation**
Se realizo el cambio sin problemas

**Comment by vrotmanh** [comment]
**Verification**
Se probo el programa y todo sigue funcionando correctamente.

**Comment by vrotmanh** [comment]
**Postfactoring**
No se encontraron errores
