### ISSUE TITLE
[RS10] Soportar circuito en paralelo con varias resistencias

### ISSUE THREAD

**Issue by javierdiazp** [IsmaelAlvarez/logisim#11]
El circuito deberá soportar varias resistencias en paralelo para lo cual hay que hacer cálculo de resistencias equivalentes y de caídas de voltaje.
- [x] Initialization
- [x] Concept Location
- [x] Impact Analysis
- [x] Prefactoring
- [x] Change Propagation
- [x] Verification
- [x] Postfactoring

**Comment by vrotmanh** [comment]
**Initialization**
Se debe poder generar un circuito con varias resistencia en paralelo y que estas se sumen correctamente.

**Comment by vrotmanh** [comment]
**Concept Location**
protosim.components.VoltageGenerator, protosim.components.Resistor, logisim.comp.Component, logisim.std.io.Io

**Comment by vrotmanh** [comment]
**Impact Analysis**
TODO

**Comment by vrotmanh** [comment]
**Prefactoring**
Se ocupará el grafo generado en AllComponents.
Se agregará una función que recorre el grafo y determina cuando se bifurca. En esos casos se determina en cuantas ramas y se va calculando la resistencia equivalente como corresponda. Las resistencias en serie se suman normalmente.

**Comment by vrotmanh** [comment]
**Change Propagation**
Se realizo el cambio

**Comment by vrotmanh** [comment]
**Verification**
Se probo el programa y se encontró un error en el caso particular en que se bifurca y luego se vuelven a juntar las ramas y poseen mas resistencias luego de volver a juntarse.

**Comment by vrotmanh** [comment]
**Postfactoring**
Se trabajo en el error, se pudo arreglar en la mayoría de los casos pero hay casos en los que falla aun que no se pudo determinar con exactitud cuando. Esto ocurre solamente en circuitos bien complejos y el error es bastante pequeño.
