### ISSUE TITLE
[RS13] Arreglar conexión de pines de 32 bits

### ISSUE THREAD

**Issue by paolocurotto** [IsmaelAlvarez/logisim#14]
Se debe arreglar que al conectar un pin de 32 bits a la entrada de dos o más compuertas lógicas de Chip, sólo se actualize la salida de una de las compuertas conectadas, en vez de actualizar correctamente todas las salidas. 

Ref: RU11
- [x] Initialization
- [x] Concept Location
- [x] Impact Analysis
- [ ] Prefactoring
- [ ] Change Propagation
- [ ] Verification
- [ ] Postfactoring

**Comment by IsmaelAlvarez** [comment]
Este requisito esta relacionado con el RS12, pues el bug es parte de que un cable se conecte a varios pines.

**Comment by IsmaelAlvarez** [comment]
se realizaron casos de pruebas para el correcto funcionamiento de los bugs y se logro ver que funcionaban correctamente.
