### ISSUE TITLE
[RS14] Mejorar protoboard

### ISSUE THREAD

**Issue by paolocurotto** [IsmaelAlvarez/logisim#16]
Se deben mejorar aspectos estéticos de la protoboard, algunos de estos son: zoom en la protoboard, accesibilidad del menú de componentes, etc.

Ref: RU11
- [x] Initialization
- [x] Concept Location
- [x] Impact Analysis
- [x] Prefactoring
- [ ] Change Propagation
- [ ] Verification
- [ ] Postfactoring

**Comment by IsmaelAlvarez** [comment]
se logro finalmente implementar el zoom in y el zoom out en el meno de la protoboard, falta afinar detalles estéticos y analizar el alcance en el código
