### ISSUE TITLE
[RS03] Soportar circuitos en serie con varias resistencias

### ISSUE THREAD

**Issue by dintrans** [IsmaelAlvarez/logisim#2]
El circuito deberá soportar varias resistencias en serie para lo cual hay que hacer cálculo de resistencias equivalentes y de caídas de voltaje.
- [x] Initialization
- [x] Concept Location
- [x] Impact Analysis
- [x] Prefactoring
- [x] Change Propagation
- [x] Verification
- [x] Postfactoring

**Comment by vrotmanh** [comment]
**Initialization**
Se debe poder generar un circuito con varias resistencia en serie y que estas se sumen correctamente.

**Comment by vrotmanh** [comment]
**Concept Location**
protosim.components.VoltageGenerator, protosim.components.Resistor, logisim.comp.Component, logisim.std.io.Io

**Comment by vrotmanh** [comment]
**Impact Analysis**
TODO

**Comment by vrotmanh** [comment]
**Prefactoring**
Se implementará un grafo que irá añadiendo todas las conexiones. Luego se agregará una función que recorra el grafo y calcule resistencia equivalente entre 2 puntos del circuito. Para resistencia en serie es simplemente sumarlas y ver que el circuito este cerrado y con una fuente de voltage conectada.

Se creará una clase tipo singleton llamada AllComponents, en esta se ira agregando cada componente que el usuario añade. Así se ira generando el grafo.

**Comment by vrotmanh** [comment]
**Change Propagation**
Se realizo el cambio

**Comment by vrotmanh** [comment]
**Verification**
Se probo el programa y todo sigue funcionando correctamente.

**Comment by vrotmanh** [comment]
**Postfactoring**
No se encontraron errores
