### ISSUE TITLE
[RS06] Implementar Capacitor

### ISSUE THREAD

**Issue by dintrans** [IsmaelAlvarez/logisim#6]
Se debe implementar el componente Capacitor, desplegable en el canvas de Logisim. Este objeto, conectado a una fuente de energía, debe simular el proceso de carga simple; y cuando no está conectado, el proceso de descarga correspondiente. 

Finalmente, el capacitor deberá poder quemarse al recibir un voltaje mayor que el voltaje para el que fue diseñado y dejar de ser funcional a un voltaje menor.

Ref:
RU06
- [x] Initialization
- [x] Concept Location
- [x] Impact Analysis
- [x] Prefactoring
- [x] Change Propagation
- [x] Verification
- [x] Postfactoring
- [x] Conclusión

**Comment by Sergio-P** [comment]
**Initialization**

Agregar capacitores como nuevos componentes de Logisim que podrán cumplir funciones de carga y descarga.

**Comment by Sergio-P** [comment]
**Concept Location**

Component, InstanceFactory, AttributeOptionInterface, Io

**Comment by Sergio-P** [comment]
**Impact Analysis**

> TODO

**Comment by Sergio-P** [comment]
**Prefactoring**

La clase `InstanceFactory` puede ser extendida para crear factories de nuevos componentes, los atributos propios del componente deben definirse usando la interfaz `AttributeOptionInterface` y ser incluidas en `Io`. Al hacer override de los métodos de `InstanceFactory` se puede implementar parte de la lógica y el dibujo del componente en el canvas.

**Comment by Sergio-P** [comment]
**Change Propagation**

Se creó una nueva clase `Capacitor` para crear un factory al componente, además se modificó la clase `Io` para agregar los atributos propios de los capacitores (capacitancia, multiplicador de capacitancia)

**Comment by Sergio-P** [comment]
**Verification**

Se comprobó usando el componente y creando circuitos, el componente no presenta conflictos. No necesita postfactoring.

**Comment by Sergio-P** [comment]
**Postfactoring**

No se encontraron errores que sean necesarios reparar.

**Comment by Sergio-P** [comment]
**Conclusión**

El componente se comporta correctamente en circuitos simples, falta extender su comportamiento a circuitos más complejos, este cambio no es trivial dado que depende de la interacción con otros capacitores y resistencias, por lo que se considera parte de otro requisito futuro.
