### ISSUE TITLE
[RS07] Implementar Chip Integrado 555

### ISSUE THREAD

**Issue by dintrans** [IsmaelAlvarez/logisim#7]
Se deberá implementar el componente Chip Integrado 555, desplegable en el canvas de Logisim. El objeto deberá simular la operación del temporizador, que es estándar en esta clase de chip. 

Finalmente, el chip deberá poder quemarse al recibir un voltaje mayor que el voltaje para el que fue diseñado y dejar de ser funcional a un voltaje menor.

Ref:
RU07
- [x] Initialization
- [x] Concept Location
- [x] Impact Analysis
- [x] Prefactoring
- [x] Change Propagation
- [x] Verification
- [x] Postfactoring

**Comment by dmadariaga** [comment]
**Initialization**

Agregar Chips del tipo [Circuito Integrado 555](https://es.wikipedia.org/wiki/Circuito_integrado_555) como nuevos componentes de Logisim que podrán ser utilizados con sus funciones de multivibrador aestable y monoestable.

**Comment by dmadariaga** [comment]
**Concept Location**

Component, InstanceFactory, AttributeOptionInterface, Io

**Comment by dmadariaga** [comment]
**Impact Analysis**

**Comment by dmadariaga** [comment]
**Prefactoring**
Se debe considerar la utilización del reloj (ticks) proporcionados por Logisim para el manejo de tiempo que debe usar el chip.
La clase `InstanceFactory` puede ser extendida para crear factories de nuevos componentes, los atributos propios del componente deben definirse usando la interfaz AttributeOptionInterface y ser incluidas en Io. Al hacer override de los métodos de InstanceFactory se puede implementar parte de la lógica y el dibujo del componente en el canvas.

**Comment by dmadariaga** [comment]
**Change Propagation**

Se creó una nueva clase `Timer555Chip` para crear un factory al componente, además se modificó la clase `Io` para agregar los atributos propios de los capacitores (capacitancia, multiplicador de capacitancia). Se implementó el meto statico `tick` el cual es llamado por el método con el mismo nombre en la clase `CircuitState` de Logisim, con el fin de manejar el tiempo dentro del chip.

**Comment by dmadariaga** [comment]
**Verification**

Se comprobó usando el componente y creando circuitos, el componente no presenta conflictos y cumple con todas las funcionalidades requeridas . No necesita postfactoring.

**Comment by dmadariaga** [comment]
**Postfactoring**

No se encontraron errores que sean necesarios reparar.

**Comment by dmadariaga** [comment]
cerrado en #38
